runtime: nodejs
env: flex

env_variable:
  SQL_USER: root
  SQL_PASSWORD: "explosion"
  SQL_DATABASE: articles
  INSTANCE_CONNECTION_NAME: capstone-pe4:asia-southeast1:mysql-root-bangkit

beta_settings:
  cloud_sql_instances: capstone-pe4:asia-southeast1:mysql-root-bangkit
  
